version: '3'  

services: 
    backend: 
      image: minesweeper
      build:
        context: ./
        dockerfile: Dockerfile
      ports: 
        - 8080:8080
      environment:
        - DATABASE_URL=jdbc:postgresql://db:5432/postgres
        - USERNAME=postgres
        - PASSWORD=example
      container_name: minesweeper
      depends_on:
        - db

    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=example
      ports:
        - 5432:5432
      volumes:
        - ./data:/var/lib/postgresql/data
        #- ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      container_name: minesweeper-db
